FROM nvidia/cuda:11.3.0-devel-ubuntu20.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
  apt-utils \
  make \
  cmake \
  git \
  python3-dev \
  python3-pip \
  && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/Jaseci-Labs/jaseci.git
RUN cd jaseci/jaseci_core && sh install.sh  
